<a href="https://colab.research.google.com/github/GTU9/PythonStudy/blob/main/w09_note_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. Pandas 라이브러리

### 01. 데이터 가져오기

In [3]:
#@title CSV 파일 내용 가져오기
with open("weather_data.csv") as data_file:
  data=data_file.readlines()
  print(data)

['day,temp,condition\n', 'Monday,12,Sunny\n', 'Tuesday,14,Rain\n', 'Wednesday,15,Rain\n', 'Thursday,14,Cloudy\n', 'Friday,21,Sunny\n', 'Saturday,22,Sunny\n', 'Sunday,24,Sunny']

In [6]:
#@title 데이터 정리하기
import csv
with open("weather_data.csv") as data_file:
    data = csv.reader(data_file)
    print(data)
    for row in data:
        print(row)

['day', 'temp', 'condition']
['Monday', '12', 'Sunny']
['Tuesday', '14', 'Rain']
['Wednesday', '15', 'Rain']
['Thursday', '14', 'Cloudy']
['Friday', '21', 'Sunny']
['Saturday', '22', 'Sunny']
['Sunday', '24', 'Sunny']

In [19]:
#@title 온도만 별도의 리스트로 저장하기
with open("weather_data.csv") as data_file:
    data = csv.reader(data_file)
    temperatures = []
    print(data)
    for row in data:
        if row[1] != 'temp':
            temperatures.append(row[1])
    print(temperatures)
    temp=0
    for i in range(len(temperatures)):
      temp+=int(temperatures[i])
    temp=round(float(temp/len(temperatures)),2)
    print(f"평균온도 {temp}")

<_csv.reader object at 0x7b418161bd80>
['12', '14', '15', '14', '21', '22', '24']
평균온도 17.43

### 02. Pandas 이용하기
* [pandas documentation](https://pandas.pydata.org/docs/)

In [ ]:
#@title 현재 pandas 버전 확인
import pandas as pd
print(pd.__version__)

2.0.3

In [20]:
#@title pandas 로 csv 파일 읽어오기
import pandas

data = pandas.read_csv("weather_data.csv")
print(data)

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny
5   Saturday    22     Sunny
6     Sunday    24     Sunny

In [21]:
print(type(data["temp"]))

<class 'pandas.core.series.Series'>

In [25]:
#@title dataframe 을 dictionary 로 저장하기
data_dict=data.to_dict()
print(data_dict)
print(type(data_dict))

{'day': {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}, 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24}, 'condition': {0: 'Sunny', 1: 'Rain', 2: 'Rain', 3: 'Cloudy', 4: 'Sunny', 5: 'Sunny', 6: 'Sunny'}}
<class 'dict'>

In [26]:
#@title series 를 list 로 저장하기
temp_list=data["temp"].to_list()
print(temp_list)
print(type(temp_list))

[12, 14, 15, 14, 21, 22, 24]
<class 'list'>

In [27]:
#@title 평균 온도 계산하기
print(data["temp"].mean())

17.428571428571427

In [32]:
#@title 온도의 최고점, 최저점, 중간값
print(data["temp"].max())
print(data["temp"].min())
print(data["temp"].median())

24
12
15.0

In [34]:
#@title 금요일의 온도와 상태
print(data[data["day"]=="Friday"])

      day  temp condition
4  Friday    21     Sunny

In [36]:
#@title 온도가 가장 높은 요일의 상태
print(data[data["temp"]==data["temp"].max()])

      day  temp condition
6  Sunday    24     Sunny

In [44]:
#@title 월요일의 온도를 화씨로 변경해서 출력
Monday=data[data["day"]=="Monday"]
Monday_temp=int(Monday.temp.iloc[0])
Monday_temp=(Monday_temp*9/5)+32
print(Monday_temp)

53.6

In [46]:
#@title 딕셔너리를 데이터프레임으로 변경하기
new_data = {
    'day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    'temp': [24, 26, 22, 29, 21, 25, 28],
    'condition': ['Sunny', 'Cloudy', 'Rainy', 'Windy', 'Sunny', 'Cloudy', 'Rainy']
}

new_data_frame=pandas.DataFrame(new_data)
print(new_data_frame)

         day  temp condition
0     Monday    24     Sunny
1    Tuesday    26    Cloudy
2  Wednesday    22     Rainy
3   Thursday    29     Windy
4     Friday    21     Sunny
5   Saturday    25    Cloudy
6     Sunday    28     Rainy

In [ ]:
#@title csv 파일로 저장하기
new_data_frame.to_csv("new_data.csv")

## 02. 데이터 분석

### 데이터 수집

In [52]:
import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business,NaN,NaN
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,NaN,NaN
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business,NaN,NaN
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS,NaN,NaN
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business,NaN,NaN

### 데이터 전처리
* dataframe 에는 몇 개의 row가 있습니까?
* 몇 개의 column이 있나요?
* column의 label은 무엇인가요? column에 이름이 있나요?
* dataframe에 누락된 값이 있나요?
* dataframe에 잘못된 데이터가 포함되어 있지는 않나요?

In [63]:
df.shape

(51, 8)

In [64]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group', 'Unnamed: 6',
       'Unnamed: 7'],
      dtype='object')

In [65]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
0,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,True,True
7,False,False,False,False,False,False,True,True
8,False,False,False,False,False,False,True,True
9,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,True,True
11,False,False,False,False,False,False,True,True
12,False,False,False,False,False,False,True,True
13,False,False,False,False,False,False,True,True
14,False,False,False,False,False,False,True,True
15,False,False,False,False,False,False,True,True
16,False,False,False,False,False,False,True,True
17,False,False,False,False,False,False,True,True
18,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,True,True
22,False,False,False,False,False,False,True,True
23,False,False,False,False,False,False,True,True
24,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,True,True
27,False,False,False,False,False,False,True,True
28,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,True,True
30,False,False,False,False,False,False,True,True
31,False,False,False,False,False,False,True,True
32,False,False,False,False,False,False,True,True
33,False,False,False,False,False,False,True,True
34,False,False,False,False,False,False,True,True
35,False,False,False,False,False,False,True,True
36,False,False,False,False,False,False,True,True
37,False,False,False,False,False,False,True,True
38,False,False,False,False,False,False,True,True
39,False,False,False,False,False,False,True,True
40,False,False,False,False,False,False,True,True
41,False,False,False,False,False,False,True,True
42,False,False,False,False,False,False,True,True
43,False,False,False,False,False,False,True,True
44,False,False,False,False,False,False,True,True
45,False,False,False,False,False,False,True,True
46,False,False,False,False,False,False,True,True
47,False,False,False,False,False,False,True,True
48,False,False,False,False,False,False,True,True
49,False,False,False,False,False,False,True,True
50,False,True,True,True,True,True,True,True

In [67]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS,NaN,NaN
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS,NaN,NaN
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS,NaN,NaN
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS,NaN,NaN
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
clean_df = df.dropna(thresh=2)

In [69]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS,NaN,NaN
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS,NaN,NaN
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS,NaN,NaN
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS,NaN,NaN
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS,NaN,NaN

### 문제 해결하기

Q. 초봉이 가장 높은 대학 전공 찾기

In [70]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [ ]:
clean_df['Starting Median Salary'].max()

74300.0

In [ ]:
clean_df['Starting Median Salary'].idxmax()

43

In [ ]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [71]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [75]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Unnamed: 6                                           NaN
Unnamed: 7                                           NaN
Name: 43, dtype: object

Q. 중간 경력 봉급이 가장 높은 대학 전공은? 이 전공 졸업생들은 얼마를 벌까요? (중간 경력은 10년 이상의 경력으로 정의합니다.)

In [78]:
clean_df["Mid-Career Median Salary"].max()

107000.0

In [77]:
clean_df["Mid-Career Median Salary"].idxmax()

8

In [76]:
clean_df["Undergraduate Major"][8]

'Chemical Engineering'

In [79]:
max_mid_career_salary = clean_df["Mid-Career Median Salary"].max()
max_mid_career_major = clean_df["Undergraduate Major"][8]
print(f"Index for the max mid career salary: ${max_mid_career_salary}")
print(f"Index for the max mid career major: {max_mid_career_major}")

Index for the max mid career salary: $107000.0
Index for the max mid career major: Chemical Engineering

Q. 초봉이 가장 낮은 대학 전공은 무엇이며 졸업 후 졸업생은 얼마를 벌까요?

In [ ]:
clean_df['Starting Median Salary'].min()

34000.0

In [ ]:
clean_df['Starting Median Salary'].idxmin()

49

In [ ]:
clean_df['Undergraduate Major'][49]

'Spanish'

In [ ]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

Q. 중간 경력 봉급이 가장 낮은 대학 전공은 무엇이며 이 학위로 얼마를 벌 수 있을까요?

In [81]:
clean_df['Mid-Career Median Salary'].min()

52000.0

In [80]:
clean_df['Mid-Career Median Salary'].idxmin()

18

In [82]:
clean_df.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Unnamed: 6                                 NaN
Unnamed: 7                                 NaN
Name: 18, dtype: object

Q. 위험도가 가장 낮은 전공은 무엇인가요?
  - 위험도가 낮다는 것은 최저 급여와 최고 급여의 차이가 적은 학위 입니다.
  - 90번째 백분위수(상위 10%)와 10번째 백분위수(하위 10%)의 소득 차이

In [84]:
clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [85]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [97]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

In [98]:
clean_df.insert(1, 'Spread', spread_col)

ValueError: cannot insert Spread, already exists

In [99]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business,NaN,NaN
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM,NaN,NaN
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business,NaN,NaN
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS,NaN,NaN
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business,NaN,NaN

In [100]:
low_risk = clean_df.sort_values('Spread')

In [101]:
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

Q. 잠재력이 가장 높은 전공은 무엇인가요?
  - 중간 경력의 90번째 백분위수(상위 10%)가 가장 높은 상위 학과

In [102]:
clean_df.sort_values("Mid-Career 90th Percentile Salary").tail()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM,NaN,NaN
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM,NaN,NaN
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM,NaN,NaN
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business,NaN,NaN
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business,NaN,NaN

In [103]:
clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False).head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business,NaN,NaN
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business,NaN,NaN
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM,NaN,NaN
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM,NaN,NaN
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM,NaN,NaN

Q. 봉급에서 가장 큰 분포를 보이는 학위는?

In [104]:
clean_df.sort_values('Spread', ascending=False).head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business,NaN,NaN
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business,NaN,NaN
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM,NaN,NaN
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business,NaN,NaN
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS,NaN,NaN

In [105]:
clean_df.sort_values('Mid-Career Median Salary', ascending=False).head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Unnamed: 6,Unnamed: 7
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM,NaN,NaN
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM,NaN,NaN
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM,NaN,NaN
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM,NaN,NaN
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business,NaN,NaN

Q. 분야(Group)별 평균 봉급은 얼마인가요?

In [106]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Unnamed: 6,Unnamed: 7
Group,,,,,,,,
Business,12,12,12,12,12,12,0,0
HASS,22,22,22,22,22,22,0,1
STEM,16,16,16,16,16,16,0,0

In [109]:
clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Unnamed: 6
Group,,,,,,
Business,103958.333333,44633.333333,75083.333333,43566.666667,147525.000000,NaN
HASS,95218.181818,37186.363636,62968.181818,34145.454545,129363.636364,NaN
STEM,101600.000000,53862.500000,90812.500000,56025.000000,157625.000000,NaN

## 03. 실습 과제

샘플 프로젝트

* [타이타닉 데이터](https://www.kaggle.com/competitions/titanic/data?select=train.csv)

* 성별에 따른 생존율은 얼마인가요?

In [ ]:
import pandas as pd

data = pd.read_csv("train.csv")

women = data.loc[data.Sex == "female"]["Survived"]
rate_survived_women = sum(women) / len(women)
print(f"Female survival rate: {round(rate_survived_women, 2) * 100}%")

Female survival rate: 74.0%
Male survival rate: 19.0%